### ISSUE TITLE
セレクトボックスのカラーがダークモードでデフォルトになっている

### ISSUE THREAD

**Issue by yamanoku** [tagucch/random.tagucch.dev#46]
https://github.com/tagucch/random.tagucch.dev/pull/43 にて追加されたセレクトボックスのカラーが表題の状態になっている

https://user-images.githubusercontent.com/1996642/167249159-7384ec0d-82d8-4129-bf95-ced9fc26345d.mov

## 再現環境

- Chromium 101.0.4951.54
- Safari Version 15.3
- Firefox 100

**Comment by tagucch** [comment]
再現環境まで書いてもらって本当に助かります:bow:
調査して修正します！

**Comment by tagucch** [comment]
[pacocoursey/next\-themes: Perfect Next\.js dark mode in 2 lines of code\. Support System preference and any other theme with no flashing](https://github.com/pacocoursey/next-themes)
next-themesの使い方が間違っているかもしれないので再確認する

**Comment by tagucch** [comment]
```ts
const { theme } = useTheme()
```
で取得したテーマを利用しているのはプルダウンのコンポーネントだけなので、ここで取得するthemeに問題がありそう

**Comment by tagucch** [comment]
上記は問題なかったし、`isLightMode`もtrue/falseに正しく分岐できていたのでまた別のところが原因ぽい

**Comment by tagucch** [comment]
> 上記は問題なかった

これはページロード後に正しく値が入っているということだった。

ページロード時にconsole.log()で確認してみたところ、`theme`はundefinedだった。
なのでライフサイクルフックを正しく設定すればいいのではないか。

**Comment by tagucch** [comment]
useEffectを使って修正したが、これだとデフォルトがライトモードなのでダークモードでページを表示すると色の切り替わりにラグがあった。
uhyoさんの助言によりuseEffectをuseLayoutEffectにすることで解決した。
https://twitter.com/uhyo_/status/1523318067639427076

**Comment by yamanoku** [comment]
初回アクセス時（シークレットウィンドウ）だとまだ直ってないような感じです
<img width="1078" alt="スクリーンショット 2022-05-09 11 16 42" src="https://user-images.githubusercontent.com/1996642/167329475-f8b72fd3-d8a6-4621-93f8-3945c616c53c.png">

コード内容は読めてないですが初期値の設定があると良さそう？

**Comment by tagucch** [comment]
@yamanoku ありがとうございます:bow:
自分の手元でも再現しました。
今までの状態はプルダウンをクリックするとライトモードのカラーに変更されるんですが、シークレットウィンドウでの挙動だとずっとダークモードのカラーのままですね。
ちょっと別でIssueを切ります:bow:
