### ISSUE TITLE
セレクトボックスのカラーがダークモードでデフォルトになっている その2

### ISSUE THREAD

**Issue by tagucch** [tagucch/random.tagucch.dev#48]
#46 の続き

シークレットウィンドウで初回表示したときに #46 と同様の色(ライトモードなのにセレクトボックスだけダークモードの色)になっている。
#46 では、一度セレクトボックスをクリックするとすぐに色が元に戻ったが、今回はどんな操作をしてもダークモードの色のままになっている。

**Comment by tagucch** [comment]
@yamanoku こちらで調査・修正していきます:pray:
不具合発見してもらいまくってて本当にありがとうございます:bow:

**Comment by tagucch** [comment]
なんとなく思いついたところだと、デフォルト値をsystemにしているけどシークレットモードだとsystemから値が取れないみたいなことがありそう。
それが正解だった場合はsystemがundefinedだったらlightにするみたいな処理だけでいける、かも

**Comment by tagucch** [comment]
シークレットモードの場合はundefinedじゃなくてthemeに'system'が入っていたのでここが問題っぽい

**Comment by tagucch** [comment]
@yamanoku 解決したと思います！

**Comment by yamanoku** [comment]
対応ありがとうございました！
